apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-k8s-web-deployment
  labels:
    app: django-k8s-web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-k8s-web-deployment
  template:
    metadata:
      labels:
        app: django-k8s-web-deployment
    spec:
      containers:
      - name: django-k8s-web
        image: lhr.ocir.io/idhkis4m3p5e/django-sample-app-k8s:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: django-k8s-web-prod-env
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 20m
        env:
          - name: PORT
            value: "8000"
      imagePullSecrets:
        - name: ocirsecret


---
apiVersion: v1
kind: Service
metadata:
  name: django-k8s-web-service
  labels:
    app: django-k8s-web-deployment
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8000
    targetPort: 8000

  selector:
    app: django-k8s-web-deployment


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx-deployment
  replicas: 3 
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx
        image: lhr.ocir.io/idhkis4m3p5e/django-sample-nginx-k8s:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 50m
          requests:
            cpu: 20m
      imagePullSecrets:
        - name: ocirsecret

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-lbaas
  labels:
    app: nginx-deployment
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80

  selector:
    app: nginx-deployment