name: Build Containers & Push to OCIR

on:
  workflow_call:
  workflow_dispatch:
  pull_request:

jobs:
  test_job:
    uses: nicolinap/django-k8-sample/.github/workflows/test.yaml@main
  build:
    runs-on: ubuntu-latest
    needs: [test_job]
    env:
      DJANGO_SUPERUSER_USERNAME: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
      DJANGO_SUPERUSER_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
      DJANGO_SUPERUSER_EMAIL: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}

      MYSQL_READY: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
      MYSQL_DB: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
      MYSQL_USER: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
      MYSQL_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
      MYSQL_HOST: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
      MYSQL_PORT: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.DJANGO_SUPERUSER_USERNAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master